"""Novo

Revision ID: 5857a30b91fb
Revises: 
Create Date: 2025-09-28 23:45:38.857044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5857a30b91fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from moviedb.models.custom_types import EncryptedType
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('email_normalizado', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dta_validacao_email', sa.DateTime(timezone=True), nullable=True),
    sa.Column('com_foto', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('avatar_base64', sa.Text(), nullable=True),
    sa.Column('foto_mime', sa.String(length=32), nullable=True),
    sa.Column('usa_2fa', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('_otp_secret', EncryptedType(length=500), nullable=True),
    sa.Column('ultimo_otp', sa.String(length=6), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email_normalizado'), ['email_normalizado'], unique=True)

    op.create_table('backup2fa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hash_codigo', sa.String(length=256), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('utilizado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dta_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dta_para_remocao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup2fa_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup2fa_usuario_id'))

    op.drop_table('backup2fa')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email_normalizado'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
