"""Filmes, pessoas e relacionamentos

Revision ID: 8398a767aec3
Revises: 5857a30b91fb
Create Date: 2025-10-08 12:27:23.525497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8398a767aec3'
down_revision = '5857a30b91fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=100), nullable=False),
    sa.Column('titulo_portugues', sa.String(length=100), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
    sa.Column('lancado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('poster_base64', sa.Text(), nullable=True),
    sa.Column('poster_mime', sa.String(length=32), nullable=True),
    sa.Column('orcamento_milhares', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('receita_lancamento_milhares', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('link_trailer', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcoes_tecnicas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funcoes_tecnicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcoes_tecnicas_nome'), ['nome'], unique=True)

    op.create_table('generos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generos_nome'), ['nome'], unique=True)

    op.create_table('pessoas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('nacionalidade', sa.String(length=60), nullable=True),
    sa.Column('dta_nascimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('foto_mime', sa.String(length=32), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('e_ator', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome_artistico', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('recomenda', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'usuario_id', name='uq_filme_usuario_avaliacao')
    )
    op.create_table('equipes_tecnicas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('funcao_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcoes_tecnicas.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'pessoa_id', 'funcao_id', name='uq_filme_pessoa_funcao')
    )
    op.create_table('filme_genero',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('genero_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'genero_id', name='uq_filme_genero')
    )
    op.create_table('atuacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('ator_id', sa.Uuid(), nullable=False),
    sa.Column('personagem', sa.String(length=100), server_default='as him/herself', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['atores.id'], ),
    sa.ForeignKeyConstraint(['filme_id'], ['filme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'ator_id', 'personagem', name='uq_filme_ator_personagem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atuacoes')
    op.drop_table('filme_genero')
    op.drop_table('equipes_tecnicas')
    op.drop_table('avaliacoes')
    op.drop_table('atores')
    op.drop_table('pessoas')
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generos_nome'))

    op.drop_table('generos')
    with op.batch_alter_table('funcoes_tecnicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcoes_tecnicas_nome'))

    op.drop_table('funcoes_tecnicas')
    op.drop_table('filme')
    # ### end Alembic commands ###
