"""Mudanca para Mapped e criptografia do otp_secret

Revision ID: a79a57e1e217
Revises: 25e9cf188f41
Create Date: 2025-09-26 01:40:22.853156

"""
from alembic import op
import sqlalchemy as sa

from moviedb.models.custom_types import EncryptedType

# revision identifiers, used by Alembic.
revision = 'a79a57e1e217'
down_revision = '25e9cf188f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_backup2fa_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('com_foto',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('_otp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=EncryptedType(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('_otp_secret',
               existing_type=EncryptedType(length=500),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('com_foto',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ultimo_login')

    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup2fa_usuario_id'))
        batch_op.alter_column('usuario_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
